spring:
  application:
    name: nba_api
  mvc:
    async:
      request-timeout: 600000
  datasource:
    url: jdbc:h2:file:./data/nba_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.nbaData.nba_api: DEBUG
    reactor.netty: DEBUG
    reactor.netty.http.client: DEBUG
    io.netty: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.web.client: DEBUG
    org.apache.http: DEBUG

nba:
  api:
    timeout-seconds: 30
    filter-active-players: true
    sync-delay-ms: 500
